[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
escrow = "AEkEcM7ANVVcmUXLyMKMw89XRfYGz71ZYJJLfziqcN3v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/saif7/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "npx tsx create-codama-client.ts; npx tsx --test --no-warnings tests/*.ts"
